### PR TITLE
Update CI configuration

### PR DESCRIPTION
**Pull request by CAMOBAP**
As title. 

 _Generated by Cimas_.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Hmmm, failing on all platforms but passing Windows?

**Comment by CAMOBAP** [comment]
For some reason, `gem "metanorma-mpfd"` not being installed on Linux & OSX by at the same time on Windows it being installed

@opoudjis @ronaldtse maybe you have an idea why?

**Comment by ronaldtse** [comment]
The gem is definitely installed but encountering path issues?

```
bundler: failed to load command: metanorma (/Users/runner/hostedtoolcache/Ruby/2.6.5/x64/bin/metanorma)
444
Errno::ENOENT: No such file or directory @ rb_sysopen - documents/images/framework.png
445
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/image_size-2.0.2/lib/image_size.rb:46:in `initialize'
446
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/image_size-2.0.2/lib/image_size.rb:46:in `open'
447
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/image_size-2.0.2/lib/image_size.rb:46:in `path'
448
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/html2doc-1.0.0/lib/html2doc/mime.rb:68:in `image_resize'
449
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/isodoc-1.0.22/lib/isodoc/html_function/postprocess.rb:126:in `block in move_images'
450
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:238:in `block in each'
451
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `upto'
452
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `each'
453
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/isodoc-1.0.22/lib/isodoc/html_function/postprocess.rb:125:in `move_images'
454
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/isodoc-1.0.22/lib/isodoc/html_function/postprocess.rb:19:in `toHTML'
455
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/isodoc-1.0.22/lib/isodoc/html_function/postprocess.rb:5:in `postprocess'
456
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/isodoc-1.0.22/lib/isodoc/convert.rb:177:in `convert'
457
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/isodoc-1.0.22/lib/isodoc/html_convert.rb:18:in `convert'
458
  /Users/runner/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/metanorma-mpfd-0.3.15/lib/metanorma/mpfd/processor.rb:32:in `output'
459
```

**Comment by CAMOBAP** [comment]
@ronaldtse for ubuntu & macos, right but for docker looks like Gemfile from repo doesn't override container's one, working on thoes issues

**Comment by CAMOBAP** [comment]
@ronaldtse  Regarding `Errno::ENOENT: No such file or directory @ rb_sysopen - documents/images/framework.png`

I noted that if a document contains `:data-uri-image:` this issue doesn't happen, but if it missing we will have similar issues for all (or most of) `mn-samples-*` repos

I see two options here:
 - Update `Makefile` to do copy images `sources -> documents`
 - Add `:data-uri-image:` to each document

P.S. `:data-uri-image:` looks like magic to me, how exactly metanorma lookup original image path?
P.P.S Still no understanding why it works on windows 'out-of-box'

**Comment by ronaldtse** [comment]
> Add :data-uri-image: to each document

This is the correct method as it embeds the image inside the output XML file.

**Comment by CAMOBAP** [comment]
Docker issue will be addressed separatelly https://github.com/metanorma/mn-samples-mpfa/issues/20

**Pull request merged**
