### PR TITLE
#7 add travis & appveyor CI

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #7

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 please help change `doctypes.env` to the solution given in #6 . Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP795 hmmm, this merge removed all the Makefiles. How am I supposed to locally compile these documents using a Bundler Gemfile?

**Comment by CAMOBAP** [comment]
@ronaldtse if we use this as template Gemfile will be taken from the common directory (like in another `mn-templates-*`)

**Comment by CAMOBAP** [comment]
As you can see in https://travis-ci.com/metanorma/mpfd-documents/jobs/218935206 logs Gemfile appears there

**Comment by ronaldtse** [comment]
No, this is not a template directory -- this is a demo directory...

**Comment by CAMOBAP** [comment]
Ok, I will revert this PR back

**Comment by ronaldtse** [comment]
@CAMOBAP795 but please keep the new attributes for the `.adoc` files, they are useful. In addition, can you also use the Makefiles from the newer repos (e.g. csd-vpoll) since they work with `metanorma.yml`?

I know this repo is a bit tricky because it's the first repo that contains hierarchical documents. We need to establish some best practices here.

Thanks.

**Comment by CAMOBAP** [comment]
cb4ec016 reverted

*failed because https://github.com/metanorma/metanorma-cli/issues/103

**Pull request merged**
